### ISSUE TITLE
Blue hover doesn't work once clicked

### ISSUE THREAD

**Issue by abhigyank** [abhigyank/RPSLS-js#5]
The blue overlay that appers on hovering an option, doesn't appear the next time once an option is chosen to be played.

**Comment by sahilarora535** [comment]
I found the cause of the bug. Basically, when you are doing this:
`setTimeout(function(){choice.style.background ="none";},1000);`
what it's doing is that it's adding `style` directly to the HTML tag, which overrides the default CSS mentioned in your CSS file.

On click, the element becomes:
`<li id="scissor" onclick="game(this)" style="background: transparent none repeat scroll 0% 0%;">
      <img src="images/scissor.png" alt="scissor">
    </li>`

**Comment by sahilarora535** [comment]
The issue has been resolved, the javascript was adding styles inline, which were in turn overriding the `hover` style defined in `styles.css`. Used `onmouseover` and `onmouseout` to resolve.

**Comment by abhigyank** [comment]
After clicking a choice, the blue hover comes only after we mouse out and the in. Not fixed properly.

**Comment by abhigyank** [comment]
This issue has been resolved with PR #6, by changing the script.js file . choice.style.background ="none" has been changed to choice.style.background ="".
